# Generated by Django 3.0.5 on 2020-05-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('index', models.PositiveIntegerField(blank=True, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='cena')),
                ('model', models.CharField(blank=True, max_length=20, null=True)),
                ('id_car', models.BigIntegerField(blank=True, null=True, verbose_name='ID samochodu')),
                ('production_year', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='rok produkcji')),
                ('mileage', models.CharField(blank=True, max_length=20, null=True, verbose_name='przebieg')),
                ('capacity', models.CharField(blank=True, max_length=20, null=True, verbose_name='pojemność')),
                ('fuel', models.CharField(blank=True, max_length=20, null=True, verbose_name='rodzaj paliwa')),
                ('date_ad', models.CharField(blank=True, max_length=20, null=True, verbose_name='data dodania')),
                ('make', models.CharField(blank=True, max_length=20, null=True, verbose_name='marka')),
                ('is_activ', models.BooleanField(blank=True, null=True)),
                ('new_price', models.PositiveIntegerField(blank=True, null=True, verbose_name='nowa cena')),
            ],
            options={
                'db_table': 'car',
                'managed': False,
            },
        ),
    ]
