# Generated by Django 3.0.5 on 2020-05-14 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('index', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.TextField(blank=True, null=True)),
                ('model', models.TextField(blank=True, null=True)),
                ('id_car', models.IntegerField(blank=True, null=True)),
                ('production_year', models.IntegerField(blank=True, null=True)),
                ('mileage', models.TextField(blank=True, null=True)),
                ('capacity', models.TextField(blank=True, null=True)),
                ('fuel', models.TextField(blank=True, null=True)),
                ('date_ad', models.TextField(blank=True, null=True)),
                ('make', models.TextField(blank=True, null=True)),
                ('is_activ', models.IntegerField(blank=True, null=True)),
                ('new_price', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'car',
                'managed': False,
            },
        ),
    ]
