# Generated by Django 3.0.5 on 2020-06-23 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samochody', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fuels',
            options={},
        ),
        migrations.AlterModelOptions(
            name='makes',
            options={},
        ),
        migrations.AlterModelOptions(
            name='models',
            options={},
        ),
    ]
