# Generated by Django 3.0.5 on 2020-06-26 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samochody', '0003_auto_20200626_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='models',
            options={'managed': True},
        ),
    ]
