# Generated by Django 3.0.5 on 2020-07-02 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samochody', '0004_auto_20200626_1318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='models',
            options={'managed': False},
        ),
    ]
