# Generated by Django 3.0.5 on 2020-05-27 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samochody', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='car',
            table='cars',
        ),
    ]
